- hosts: all
  vars:
    location: "/srv/mirror"
    mirror_list:
      # Common Server
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
      # OCP
      - rhel-7-server-ose-3.11-rpms
      - rhel-7-fast-datapath-rpms
      #SCL
      - rhel-server-rhscl-7-rpms
      # HA
      - rhel-ha-for-rhel-7-server-rpms
      # SSO
      - jb-eap-7.2-for-rhel-7-server-rpms
      - rh-sso-7.3-for-rhel-7-server-rpms
      # Ceph 3
      - rhel-7-server-rhceph-3-mon-rpms
      - rhel-7-server-rhceph-3-tools-rpms
      - rhel-7-server-rhceph-3-textonly-rpms
      - rhel-7-server-rhceph-3-osd-rpms
      # Ceph 4
      - rhel-7-server-ansible-2.8-rpms
      - rhel-7-server-rhceph-4-mon-rpms
      - rhel-7-server-rhceph-4-osd-rpms
      - rhel-7-server-rhceph-4-tools-rpms
  tasks:
    - name: Check mirror path is exist
      file:
        path: "{{ location }}"
        state: directory


    - name: Update specific repos
      command: "/usr/bin/reposync --newest-only --gpgcheck -l --downloadcomps --download-metadata --repoid={{ item }} --download_path={{ location }} --exclude=*.repodata"
      with_items:
        - "{{ mirror_list }}"

    - name: Hotfix - Keep /srv/mirror/rhel-7-server-rpms/.repodata Empty
      file:
        path: /srv/mirror/rhel-7-server-rpms/.repodata
        state: absent

    - name: Update metadata of repos
      command: "createrepo --update {{ location }}/{{ item }}"
      with_items:
        - "{{ mirror_list }}"
