- hosts: all
  vars:
    location: "/srv/mirror"
    mirror_list:
      # Basic
      - rhel-8-for-x86_64-appstream-eus-rpms
      - rhel-8-for-x86_64-baseos-eus-rpms
      - ansible-2.9-for-rhel-8-x86_64-rpms
      - rhel-8-for-x86_64-highavailability-eus-rpms
      # CNV
      - cnv-2.4-for-rhel-8-x86_64-rpms
  tasks:
    - name: Check mirror path is exist
      file:
        path: "{{ location }}"
        state: directory

    - name: Update specific repos
      command: "dnf reposync --newest-only --downloadcomps --download-metadata --repoid={{ item }} --downloaddir={{ location }}"
      with_items:
        - "{{ mirror_list }}"
      become: true

    - name: Make sure permission 655
      file:
        path: "{{ location }}/{{ item }}"
        owner: root
        group: root
        mode: '0655'
        recurse: yes
      with_items:
        - "{{ mirror_list }}"
      become: true
