- hosts: all
  vars:
    location: "/srv/mirror"
    mirror_list:
      # Basic
      - rhel-8-for-x86_64-appstream-rpms
      - rhel-8-for-x86_64-baseos-rpms
      - ansible-2.9-for-rhel-8-x86_64-rpms
      - jb-eap-7.2-for-rhel-8-x86_64-rpms
  tasks:
    - name: Check mirror path is exist
      file:
        path: "{{ location }}"
        state: directory

    - name: Update specific repos
      command: "/usr/bin/reposync --newest-only --download-metadata --repoid={{ item }} --downloaddir={{ location }}"
      with_items:
        - "{{ mirror_list }}"
      become: true

