- hosts: all
  vars:
    location: "/srv/mirror"
  tasks:
    - name: Check mirror path is exist
      file:
        path: "{{ location }}"
        state: directory

    - name: Update specific repos
      command: "/usr/bin/reposync --gpgcheck -l --downloadcomps --download-metadata --repoid={{ item }} --download_path={{ location }}"
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-optional-rpms
        - rhel-7-server-ose-3.9-rpms

    - name: Update metadata of repos
      command: "createrepo --update {{ location }}"
