- hosts: all
  vars:
    location: "/srv/mirror"
    mirror_list:
      # Common Server
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
      # OCP
      - rhel-7-server-ose-3.9-rpms
      - rhel-7-server-ose-3.10-rpms
      - rhel-7-server-ose-3.11-rpms
      - rhel-7-fast-datapath-rpms
      # OSP 13
      - rhel-7-server-rh-common-rpms
      - rhel-ha-for-rhel-7-server-rpms
      - rhel-7-server-openstack-13-rpms
      - rhel-7-server-openstack-13-devtools-rpms
      # HA
      - rhel-ha-for-rhel-7-server-rpms
  tasks:
    - name: Check mirror path is exist
      file:
        path: "{{ location }}"
        state: directory

    - name: Update specific repos
      command: "/usr/bin/reposync --newest-only --gpgcheck -l --downloadcomps --download-metadata --repoid={{ item }} --download_path={{ location }}"
      with_items:
        - "{{ mirror_list }}"

    - name: Update metadata of repos
      command: "createrepo --update {{ location }}/{{ item }}"
      with_items:
        - "{{ mirror_list }}"
